/**
 * Unified Backend API — использует HTTP API (Python FastAPI).
 * Все импорты api.* остаются без изменений.
 */
import {
  authEndpoint,
  tasksEndpoint,
  projectsEndpoint,
  tablesEndpoint,
  activityEndpoint,
  messagesEndpoint,
  statusesEndpoint,
  prioritiesEndpoint,
  notificationPrefsEndpoint,
  automationEndpoint,
  notificationQueueEndpoint,
  notificationEventsEndpoint,
  notificationsEndpoint,
  clientsEndpoint,
  contractsEndpoint,
  employeesEndpoint,
  dealsEndpoint,
  oneTimeDealsEndpoint,
  accountsReceivableEndpoint,
  docsEndpoint,
  foldersEndpoint,
  weeklyPlansEndpoint,
  calendarEndpoint,
  meetingsEndpoint,
  contentPostsEndpoint,
  shootPlansEndpoint,
  departmentsEndpoint,
  financeEndpoint,
  bpmEndpoint,
  inventoryEndpoint,
  funnelsEndpoint,
  integrationsMetaEndpoint,
  integrationsSiteEndpoint,
  integrationsTelegramEndpoint,
  integrationsTelegramPersonalEndpoint,
  publicContentPlanEndpoint,
} from "../services/apiClient";

export const api = {
  users: authEndpoint,

  tasks: tasksEndpoint,
  projects: projectsEndpoint,

  tables: tablesEndpoint,
  activity: activityEndpoint,
  messages: messagesEndpoint,
  statuses: statusesEndpoint,
  priorities: prioritiesEndpoint,
  notificationPrefs: notificationPrefsEndpoint,
  automation: automationEndpoint,
  notificationQueue: notificationQueueEndpoint,
  notificationEvents: notificationEventsEndpoint,
  notifications: notificationsEndpoint,

  clients: clientsEndpoint,
  contracts: contractsEndpoint,
  oneTimeDeals: oneTimeDealsEndpoint,
  accountsReceivable: accountsReceivableEndpoint,
  employees: employeesEndpoint,
  deals: dealsEndpoint,

  docs: docsEndpoint,
  folders: foldersEndpoint,
  weeklyPlans: weeklyPlansEndpoint,
  calendar: calendarEndpoint,
  meetings: meetingsEndpoint,
  contentPosts: contentPostsEndpoint,
  shootPlans: shootPlansEndpoint,

  departments: departmentsEndpoint,
  finance: financeEndpoint,
  bpm: bpmEndpoint,
  inventory: inventoryEndpoint,
  funnels: funnelsEndpoint,

  integrationsMeta: integrationsMetaEndpoint,
  integrationsSite: integrationsSiteEndpoint,
  integrationsTelegram: integrationsTelegramEndpoint,
  integrationsTelegramPersonal: integrationsTelegramPersonalEndpoint,

  publicContentPlan: publicContentPlanEndpoint,
};
